/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { ZwcButtonProps } from 'src/types';

const ZwcButton1: any = styled('div')({
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `37px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle: any = styled('div')({
  backgroundColor: `rgba(0, 158, 247, 1)`,
  borderRadius: `3px`,
  width: `390px`,
  height: `37px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Submit: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `167px`,
  top: `8px`,
});

function ZwcButton(props: ZwcButtonProps): JSX.Element {
  return (
    <ZwcButton1 className={props.className}>
      <Rectangle></Rectangle>
      <Submit>{`SUBMIT`}</Submit>
    </ZwcButton1>
  );
}

export default ZwcButton;
