/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { ZwcInputProps } from 'src/types';

const ZwcInput1: any = styled('div')({
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `52px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle: any = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(232, 233, 234, 1)`,
  width: `390px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function ZwcInput(props: ZwcInputProps): JSX.Element {
  return (
    <ZwcInput1 className={props.className}>
      <Rectangle></Rectangle>
    </ZwcInput1>
  );
}

export default ZwcInput;
